name: Python application

on:
  push:
    branches: [ v1.4 ]
  pull_request:
    branches: [ v1.4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir data
        mv .github/workflow/settings.json data/settings.json
        mv .github/workflow/sessionPub.pem data/sessionPub.pem
        mv .github/workflow/sessionPriv.pem data/sessionPriv.pem 
    - name: Start jimiCore
      run: |
        python jimi_core.py
