name: Python application

on:
  push:
    branches: [ v1.4 ]
  pull_request:
    branches: [ v1.4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir data
        wget https://raw.githubusercontent.com/z1pti3/jimi/v1.4/.github/workflows/settings.json data/settings.json
        wget https://raw.githubusercontent.com/z1pti3/jimi/v1.4/.github/workflows/sessionPub.pem data/sessionPub.pem
        wget https://raw.githubusercontent.com/z1pti3/jimi/v1.4/.github/workflows/sessionPriv.pem data/sessionPriv.pem 
    - name: Start jimiCore
      run: |
        python jimi_core.py
